eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8080
ribbon:
  ReadTimeout: 60000



spring:
  application:
    name: "api-gateway"
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
      routes:


        - id: slot-management-service
          uri: lb://slot-management-service
          predicates:
            - Path=/slot-management-service/**
          filters:
            - RewritePath=/slot-management-service(?<segment>/?.*), $\{segment}

        - id: product-webapp
          uri: lb://product-webapp
          predicates:
            - Path=/**
          filters:
            - RewritePath=/product-webapp(?<segment>/?.*), $\{segment}


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

